#!/usr/bin/env bash
#installs nginx server

echo -e "updating and installing Nginx.\n"
sudo apt-get update -y -qq && \
	sudo apt-get install nginx -y


#starting the nginx service
sudo service nginx start

#allow nginx on firewall
sudo ufw allow 'Nginx HTTP'

#giving the user the ownership of the site 
sudo chown -R "$UPPER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backup default index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Creating new index
echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html

# Restarting nginx
sudo service nginx restart

echo -e "\nCompleted. ✅\n"

