#!/usr/bin/env bash
#this script displays Best School 9 times and Hi 1 time
counter=0
while [ $counter -lt 10 ]; do
	if [ $counter -eq 9 ]; then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	((counter++))
done
