#!/usr/bin/env bash
#this script displays bad luc on the 4th loop, good luck
#on the 8th loop and Best School on other loops
counter=0
while [ $counter -lt 10 ]; do
	if [ $counter -eq 3 ]; then
		echo "bad luck"
	elif [ $counter -eq 7 ]; then
                echo "good luck"
	else
		echo "Best School"
	fi
	((counter++))
done
