#!/usr/bin/env bash
#this script displays 1 to 20 but displays bad luck from China on
#the 4th, good luck from Japan on the 9th loop and bad luck
#from Italy on the 17th loop
counter=1
while [ $counter -le 20 ]; do
	case $counter in
		4) 	echo "4"
			echo "bad luck from China" ;;
		9) 	echo "9"
			echo "good luck from Japan" ;;
		17) 	echo "17"
			echo "bad luck from Italy" ;;
		*) 	echo "$counter" ;;
	esac
	((counter++))
done
