#!/usr/bin/env bash
#this script displays bad luc on the 4th loop, good luck
#on the 8th loop and Best School on other loops
counter=1
while [ $counter -le 20 ]; do
	case $counter in
		4) 	echo "4"
			echo "bad luck from China" ;;
		9) 	echo "9"
			echo "good luck from Japan" ;;
		17) 	echo "17"
			echo "bad luck from Italy" ;;
		*) 	echo "$counter" ;;
	esac
	((counter++))
done
